[package]
name = "rust_gfx_study"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.20"
winit = "0.29"
futures = "0.3"
bytemuck = "1.14"
bytemuck_derive = "1.6"
env_logger = "0.11"
pollster = "0.3"